### ISSUE TITLE
Feature Request: Filtering based on class

### ISSUE THREAD

**Issue by ChuangSheep** [kiriDevs/vplanweb#20]
Can we filter also the calss (e.g. `Q1`) instead of only specific courses?

**Comment by kiriDevs** [comment]
Sounds like a good idea, probably will be implemented as "if no courses are saved, filter for the whole class".

**Comment by kiriDevs** [comment]
Wow GitHub now has a feature that lets you create a branch right from the issue page and then have that branch visibly linked to the issue

**Comment by kiriDevs** [comment]
Merged to `main` with 71b796ef9eb08c3d6d10ca1bf5fdaa6500399d26
