### ISSUE TITLE
Make the date selection a dropdown instead of an entry field

### ISSUE THREAD

**Issue by kiriDevs** [kiriDevs/vplanweb#39]
**Help Wanted:** This PR is asking for your opinions and input.
See the "Help Wanted" section at the bottom of this PR's body for more information.
Remember to keep discussion civil and friendly.

---

## Original idea

Offer the next 2-3 weekdays or something like that. Prevents any errors by mis-typing dates or just not getting the format (especially since timestamps use a 2-digit-year instead of 4-digit).

Just hide weekend days, since those are irrelevant for substitution plans.

## Help Wanted

- What to do with holidays? Currently, there is already a plan for the first school day after the holidays.
  While that plan should in no case be considered final, it might be cool to show it for completeness,
  even when it is more than 2-3 days away.
- Could it be better to just display the next three days for which plans are available,
  with a limit of two weeks in the future?
  That could be figured out by sending `OPTIONS` requests for dates until we find 3 plans or reach the 14d limit?
  Probably filter out weekends to limit request volume (rate limits / request volume? @chuangsheep)
- What to do with historical data?
  With a dropdown going into the future, historical data would be inaccessible.
  Maybe a setting to swich back to the entry field?
  Or an "other" entry in the dropdown that allows the user to enter a custom date for one time?
  (That could also help with points 1 and 2: handling of holidays / weekends)

**Comment by ChuangSheep** [comment]
Since it's impossible for us to have more than 3 vplans in the future (i haven't seen this situation at any time yet), I might just response with all future dates. And, I'd rather use GET than OPTION, but this is another topic and not that important.

**Comment by kiriDevs** [comment]
Yep, if you would create a response that gives me the dates that would be `GET`. I just would've used `OPTIONS` if I'd have to check for existing dates myself to reduce the amount of data transferred, since we'd only need the status code (either `404` or `200`) to determine if the plan exists.

Also some way to get all existing future dates would be *super* convenient for this.
