### ISSUE TITLE
switch to turn on/off the subject filter

### ISSUE THREAD

**Issue by ItsKillerCooKiE** [kiriDevs/vplanweb#49]
Sometimes I want to look up who‘s lessons are not taking place. Having to either delete all your previous set settings or having to filter the list by yourself is annoying.

**Comment by kiriDevs** [comment]
I wonder if this switch should be placed on the `HomeScreen` or in Settings.

I'm thinking `HomeScreen` because it'd be a setting you'd want to be able to access quickly, but also `SettingsScreen` because that's where the subject filter is located.

**Comment by ItsKillerCooKiE** [comment]
I would put the switch in Settings.

**Comment by kiriDevs** [comment]
I guess I'll put it in settings then
